services:
  nginx:
    container_name: nginx
    build: nginx
    image:
      nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./AglaiaLabBE/static:/django/static
      - ./AglaiaLabBE/media:/django/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/project.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
      - vue

  django:
    build: AglaiaLabBE
    container_name: django_gunicorn
    volumes:
      - ./AglaiaLabBE:/django
    expose:
      - "8000"
    env_file:
      - AglaiaLabBE/.env
    environment:
      - DJANGO_SETTINGS_MODULE=AglaiaLabBE.settings.local
    command: gunicorn -w 2 -b 0.0.0.0:8000 --chdir /django AglaiaLabBE.wsgi:application

  vue:
    build: aglaialabfe
    container_name: vue
#    ports:
#      - "8080:80"
    expose:
      - "8080"